import cv2

src = cv2.imread("../img/123.bmp", 0)
# gau = cv2.Laplacian(src,-1)
# src = cv2.GaussianBlur(src,(3,3),1)
src = cv2.convertScaleAbs(src,alpha=3,beta=0)
# src = cv2.GaussianBlur(src,(3,3),1)
# gau = cv2.medianBlur(src,3)
gau = cv2.Laplacian(src,-1)
# gau = cv2.medianBlur(gau,3)
ret,gau = cv2.threshold(gau,0,255,cv2.THRESH_BINARY|cv2.THRESH_OTSU)
# gau = cv2.medianBlur(gau,1)
# kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3,3))
# src = cv2.morphologyEx(gau,cv2.MORPH_OPEN,kernel)
# dst = cv2.Canny(src,80,200)
cv2.imshow("gau",gau)
cv2.imshow("src",src)
# cv2.imshow("dst",dst)
cv2.waitKey(0)